### ISSUE TITLE
SubmitButton animation sequence需要更穩定

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/watchout-common-functions#30]
* 研究為什麼用setTimeout來做的animation sequence不是每一次都會很穩定的進行
* 找到解決方法

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/watchout-common-functions/commit/12feb58c65a07ec3ede344762d056be9f9c44c95 應該有改善，繼續觀察。

**Comment by wesley100002001** [comment]
暫時沒有此現象了。
