### ISSUE TITLE
當Citizen 使用 PATCH /citizen/password 應該強制登出，並清除cookie and local storage

### ISSUE THREAD

**Issue by charlieworld** [watchout-tw/watchout-common-functions#4]
當Citizen 使用 PATCH /citizen/password 應該強制登出，並清除cookie and local storage  的 Token.

註： 舊的合法Token理論上還是可以使用，只能等它過期 (365天)。

相關文件參閱 ： https://docs.core.watchout.tw/citizen/password#update-password

**Comment by chihaoyo** [comment]
完成囉！
