### ISSUE TITLE
Facebook share 使用新的 SDK

### ISSUE THREAD

**Issue by wesley100002001** [watchout-tw/watchout-common-functions#66]
現在使用的是 facebook 早期的分享方式，sharer.php
新的方式可參考：https://developers.facebook.com/docs/sharing/reference/share-dialog/#advancedtopics

**Comment by KTRNJack** [comment]
## 備註

[Quick Start Facebook SDK](https://developers.facebook.com/docs/javascript/quickstart)

[ FB 分享連結 ]( https://blog.pulipuli.info/2017/04/facebookfacebook-how-to-share-to.html )
